apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockyards-flux2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dockyards-flux2
      app.kubernetes.io/part-of: dockyards
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dockyards-flux2
        app.kubernetes.io/part-of: dockyards
      name: dockyards-flux2
    spec:
      containers:
      - image: dockyards-flux2
        name: dockyards-flux2
        imagePullPolicy: IfNotPresent
        ports:
        - name: webhook
          containerPort: 9443
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      imagePullSecrets:
      - name: dockyards-registry
      serviceAccountName: dockyards-flux2
      securityContext:
        fsGroup: 65532
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
