---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dockyards-io-v1alpha3-workloadtemplate
  failurePolicy: Fail
  name: validation.workloadtemplate.dockyards.io
  rules:
  - apiGroups:
    - dockyards.io
    apiVersions:
    - v1alpha3
    operations:
    - CREATE
    - UPDATE
    resources:
    - workloadtemplates
  sideEffects: None
