apiVersion: v1
kind: Service
metadata:
  name: webhook-service
spec:
  ports:
  - port: 443
    targetPort: webhook
  selector:
    app.kubernetes.io/name: dockyards-flux2
    app.kubernetes.io/part-of: dockyards
