---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dockyards-flux2
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dockyards.io
  resources:
  - clusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dockyards.io
  resources:
  - containerimagedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dockyards.io
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - dockyards.io
  resources:
  - deployments/status
  verbs:
  - patch
- apiGroups:
  - dockyards.io
  resources:
  - helmdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dockyards.io
  resources:
  - kustomizedeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - helmrepositories
  verbs:
  - create
  - get
  - list
  - watch
